### ISSUE TITLE
v0.9c - Crash & Exceptionlog

### ISSUE THREAD

**Issue by Vitae666** [Wiedmolol/CQAutomater#11]
5/7/2018 12:17:38 AM
System.Net.WebException: The remote name could not be resolved: 'cosmosquest.net'
   at System.Net.HttpWebRequest.GetResponse()
   at CQFollowerAutoclaimer.PFStuff.getWBData(String id)
   at CQFollowerAutoclaimer.AutoWB.<WBTimer_Elapsed>d__4.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.<>c.<ThrowAsync>b__6_1(Object state)
   at System.Threading.QueueUserWorkItemCallback.WaitCallback_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.QueueUserWorkItemCallback.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading._ThreadPoolWaitCallback.PerformWaitCallback()

**Comment by Vitae666** [comment]
Ok, so apparently CQAF crashes when I lose internet for some reason...Figured that out just a bit ago when I lost internet and it crashed.
Also, damn, you hammer the heck outta the game with requests! LOL

[ErrorLog.txt](https://github.com/Wiedmolol/CQAutomater/files/1982578/ErrorLog.txt)
[ExceptionLog.txt](https://github.com/Wiedmolol/CQAutomater/files/1982580/ExceptionLog.txt)

**Comment by saynotoid** [comment]
same here for me and it IS VERY ANNOYING!!!
i always have it running (and my isp isn't perfect) so
when im out for work or sleeping if it crashes im losing lots of hours of pvp claims etc :(:(:(

we must somehow have it reconnect each time or smth else etc for good. thx in adv

**Comment by Wiedmolol** [comment]
Might be fixed, might be not xD Tell me if it still happens in new version.
