### ISSUE TITLE
ExceptionLog

### ISSUE THREAD

**Issue by Vitae666** [Wiedmolol/CQAutomater#21]
Woke up to latest CQAF crashed and this in the ExceptionLog.

6/13/2018 4:58:50 AM
Newtonsoft.Json.JsonReaderException: Unexpected character encountered while parsing value: D. Path '', line 0, position 0.
   at Newtonsoft.Json.JsonTextReader.ParseValue()
   at Newtonsoft.Json.JsonTextReader.Read()
   at Newtonsoft.Json.Linq.JObject.Load(JsonReader reader, JsonLoadSettings settings)
   at Newtonsoft.Json.Linq.JObject.Parse(String json, JsonLoadSettings settings)
   at CQFollowerAutoclaimer.PFStuff.getWebsiteData(String id)
   at CQFollowerAutoclaimer.AutoWB.<getWebsiteData>d__9.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.<>c.<ThrowAsync>b__6_1(Object state)
   at System.Threading.QueueUserWorkItemCallback.WaitCallback_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.QueueUserWorkItemCallback.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading._ThreadPoolWaitCallback.PerformWaitCallback()

**Comment by sctknight** [comment]
I got the same error today and I can't find a solution.

**Comment by Vitae666** [comment]
Just woke up to it again today. Happened at almost the same time as last time too.
6/28/2018 5:00:12 AM

**Comment by Vitae666** [comment]
Just got back from work and started it up. Seems to have fixed itself. Guess it was something on the game side and they changed it back.
