### ISSUE TITLE
I got this error today on the latest version

### ISSUE THREAD

**Issue by sctknight** [Wiedmolol/CQAutomater#25]
28.06.2018 12:06:42
Newtonsoft.Json.JsonReaderException: Unexpected character encountered while parsing value: D. Path '', line 0, position 0.
   at Newtonsoft.Json.JsonTextReader.ParseValue()
   at Newtonsoft.Json.JsonTextReader.Read()
   at Newtonsoft.Json.Linq.JObject.Load(JsonReader reader, JsonLoadSettings settings)
   at Newtonsoft.Json.Linq.JObject.Parse(String json, JsonLoadSettings settings)
   at CQFollowerAutoclaimer.PFStuff.getWebsiteData(String id)
   at CQFollowerAutoclaimer.AutoWB.<getWebsiteData>d__9.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.<>c.<ThrowAsync>b__6_1(Object state)
   at System.Threading.QueueUserWorkItemCallback.WaitCallback_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.QueueUserWorkItemCallback.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading._ThreadPoolWaitCallback.PerformWaitCallback()

**Comment by Vitae666** [comment]
Yeah, same here. That was my ExceptionLog when it crashed on me last night at 5AM, just woke up, and it's crashing on startup.
Thinking that there was some code change in game that's causing it.
Here's what I'm getting the 2 times I tried to start it up. It references the Auction House and World Boss:

6/28/2018 1:41:34 PM
System.NullReferenceException: Object reference not set to an instance of an object.
   at CQFollowerAutoclaimer.AuctionHouse.loadAuctions(Boolean getData)
   at CQFollowerAutoclaimer.AutoWB.<getWebsiteData>d__9.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.<>c.<ThrowAsync>b__6_1(Object state)
   at System.Threading.QueueUserWorkItemCallback.WaitCallback_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.QueueUserWorkItemCallback.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading._ThreadPoolWaitCallback.PerformWaitCallback()

6/28/2018 1:42:51 PM
System.NullReferenceException: Object reference not set to an instance of an object.
   at CQFollowerAutoclaimer.AuctionHouse.loadAuctions(Boolean getData)
   at CQFollowerAutoclaimer.AutoWB.<getWebsiteData>d__9.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.<>c.<ThrowAsync>b__6_1(Object state)
   at System.Threading.QueueUserWorkItemCallback.WaitCallback_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.QueueUserWorkItemCallback.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading._ThreadPoolWaitCallback.PerformWaitCallback()

**Comment by Vitae666** [comment]
Just got back from work and started it up. Seems to have fixed itself. Guess it was something on the game side and they changed it back.

**Comment by sctknight** [comment]
I think that also because mine started working again a couple hours after posting here.

**Comment by saynotoid** [comment]
same here, was too lazy to post:)
