### ISSUE TITLE
System.Exception: Must be logged in to call this method

### ISSUE THREAD

**Issue by Vitae666** [Wiedmolol/CQAutomater#28]
Been waking up the past 2 days to this:
```
System.Exception: Must be logged in to call this method
   at PlayFab.PlayFabClientAPI.<GetUserInventoryAsync>d__58.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at CQFollowerAutoclaimer.PFStuff.<getCurrencies>d__41.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at CQFollowerAutoclaimer.Form1.<getCurr>d__35.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at CQFollowerAutoclaimer.Form1.<freeChestBox_CheckedChanged>d__43.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.<>c.<ThrowAsync>b__6_0(Object state)
```
To give some background, in order to avoid the whole "D. Path" error where, as I surmised in a previous post, means that the CQ server is offline, I created a .bat file that closes CQAF, waits 35 minutes, the starts it back up again, and I've set this on a schedule in the Task Scheduler to start at 4:58 AM every day. Have been having this run for about 20 days now without incident. Until 2 days ago. 
It's not dumping anything to any of the files (ErrorLog, ExceptionLog) just a popup that says that I have to be logged in for it to work and the above text in the box.
Then CQAF asks if I want to run the solver and then asks if my name is in the CQ board so that the WB can be run. I click Yes to all of them and then it starts up.
I close CQAF and restart it and I don't get that error or msgs. Just seems to be doing it on the overnight. But like I said, it's been over 20 days without incident.
Ideas?
Going to try extending the timeout to 45 mins. Maybe the server is taking longer to start up.

**Comment by Vitae666** [comment]
Ok, so, I guess it has nothing to do with the Server being offline.
Just had this happen to me again. I've been waking up to it for the past week, but I go to bed around 3AM and wake up at 1PM.
It happened just now at 8:30. The server isn't down. 
Nothing is being logged in any of the log texts, so I don't even know if this is the usual time for this to be happening now or not.
Same issues once I click "Continue". I get a Calc Question box asking if I want to run auto-solve now. And WB Name Question with the warning about being sure if I've enabled my username.
Dungeon is up, but if it wasn't for it always asking me about auto-solve, I'd almost assume it's Dung related, but it's not. Or at least highly unlikely if it's an error in the call to check for Dung being up. I don't know what time they normally open that up. I'd assume with the new "day" tho, which would be on server restart. Logically anyway :)
So, what the heck is happening?

![capture](https://user-images.githubusercontent.com/9310914/44032037-ee03b272-9ed3-11e8-981f-620d9730a68b.JPG)

EDIT: Ok, so just got this again at 9AM
```
See the end of this message for details on invoking 
just-in-time (JIT) debugging instead of this dialog box.

************** Exception Text **************
System.Exception: Must be logged in to call this method
   at PlayFab.PlayFabClientAPI.<GetUserInventoryAsync>d__58.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at CQFollowerAutoclaimer.PFStuff.<getCurrencies>d__41.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at CQFollowerAutoclaimer.Form1.<getCurr>d__35.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at CQFollowerAutoclaimer.Form1.<freeChestBox_CheckedChanged>d__43.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.<>c.<ThrowAsync>b__6_0(Object state)


************** Loaded Assemblies **************
mscorlib
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.3130.0 built by: NET472REL1LAST_B
    CodeBase: file:///C:/Windows/Microsoft.NET/Framework/v4.0.30319/mscorlib.dll
----------------------------------------
CQ Auto-follower-claimer-inator
    Assembly Version: 1.0.1.32372
    Win32 Version: 1.0.1.*
    CodeBase: file:///C:/Users/jweiss/Desktop/MISC/CosmosQuest/CQ%20Auto-follower-claimer-inator.exe
----------------------------------------
System.Windows.Forms
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.3130.0 built by: NET472REL1LAST_B
    CodeBase: file:///C:/windows/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms/v4.0_4.0.0.0__b77a5c561934e089/System.Windows.Forms.dll
----------------------------------------
System
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.3130.0 built by: NET472REL1LAST_B
    CodeBase: file:///C:/windows/Microsoft.Net/assembly/GAC_MSIL/System/v4.0_4.0.0.0__b77a5c561934e089/System.dll
----------------------------------------
System.Drawing
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.3130.0 built by: NET472REL1LAST_B
    CodeBase: file:///C:/windows/Microsoft.Net/assembly/GAC_MSIL/System.Drawing/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll
----------------------------------------
System.Core
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.3130.0 built by: NET472REL1LAST_B
    CodeBase: file:///C:/windows/Microsoft.Net/assembly/GAC_MSIL/System.Core/v4.0_4.0.0.0__b77a5c561934e089/System.Core.dll
----------------------------------------
System.Configuration
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.2558.0 built by: NET471REL1
    CodeBase: file:///C:/windows/Microsoft.Net/assembly/GAC_MSIL/System.Configuration/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Configuration.dll
----------------------------------------
System.Xml
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.3130.0 built by: NET472REL1LAST_B
    CodeBase: file:///C:/windows/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
Newtonsoft.Json
    Assembly Version: 11.0.0.0
    Win32 Version: 11.0.1.21818
    CodeBase: file:///C:/Users/jweiss/Desktop/MISC/CosmosQuest/Newtonsoft.Json.DLL
----------------------------------------
System.Runtime.Serialization
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.3130.0 built by: NET472REL1LAST_B
    CodeBase: file:///C:/windows/Microsoft.Net/assembly/GAC_MSIL/System.Runtime.Serialization/v4.0_4.0.0.0__b77a5c561934e089/System.Runtime.Serialization.dll
----------------------------------------
System.Numerics
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.2558.0 built by: NET471REL1
    CodeBase: file:///C:/windows/Microsoft.Net/assembly/GAC_MSIL/System.Numerics/v4.0_4.0.0.0__b77a5c561934e089/System.Numerics.dll
----------------------------------------
System.Data
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.3130.0 built by: NET472REL1LAST_B
    CodeBase: file:///C:/windows/Microsoft.Net/assembly/GAC_32/System.Data/v4.0_4.0.0.0__b77a5c561934e089/System.Data.dll
----------------------------------------

************** JIT Debugging **************
To enable just-in-time (JIT) debugging, the .config file for this
application or computer (machine.config) must have the
jitDebugging value set in the system.windows.forms section.
The application must also be compiled with debugging
enabled.

For example:

<configuration>
    <system.windows.forms jitDebugging="true" />
</configuration>

When JIT debugging is enabled, any unhandled exception
will be sent to the JIT debugger registered on the computer
rather than be handled by this dialog box.



```

**Comment by Vitae666** [comment]
Running Dung and this popped up. Might be related. Might not. But since it says something about the .Net framework, adding it to this thread.
![capture](https://user-images.githubusercontent.com/9310914/44032629-b88267b8-9ed5-11e8-93e0-5ec1b9859627.JPG)


EDIT: Ok, maybe THIS particular .Net error pictured here, is related to CQMC. Really not sure. There were 2 logs, tho 2 minutes apart. Both appear to say the same thing, but the ExceptionLog looks prettier. LOL!
[CQMCErrors.txt](https://github.com/Wiedmolol/CQAutomater/files/2282986/CQMCErrors.txt)
[ExceptionLog.txt](https://github.com/Wiedmolol/CQAutomater/files/2282987/ExceptionLog.txt)

8/13/2018 8:47:47 AM <==CQMCErrors.txt
8/13/2018 8:45:44 AM <==ExceptionLog.txt
Newtonsoft.Json.JsonReaderException: Error reading JObject from JsonReader. Path '', line 0, position 0.
   at Newtonsoft.Json.Linq.JObject.Load(JsonReader reader, JsonLoadSettings settings)
   at Newtonsoft.Json.Linq.JObject.Parse(String json, JsonLoadSettings settings)
   at CQMacroCreator.Form1.runCalcButton_Click(Object sender, EventArgs e)
   at CQMacroCreator.Form1.sendTillNoSolveButton_Click(Object sender, EventArgs e)
   at CQMacroCreator.Form1..ctor()
   at CQMacroCreator.Program.Main()

**Comment by Vitae666** [comment]
Does anyone know ANYTHING about this "Must be logged in to call this method" nonsense?!
Getting tired of this already. It's happening almost always at 8:30AM or 9AM (EST if that matters)
I can get into the game. I can play the game. I can cloud save the game. I'M LOGGED IN! And I'm getting this msg.
Eventually it clears itself up. So it's not like it has anything to do with Playfab ID/Auth Ticket being wrong.

**Comment by Vitae666** [comment]
Well, this is happening consistently now....Have had it about 10 times already today.

ExceptionLog.txt

8/17/2018 2:43:47 PM
System.NullReferenceException: Object reference not set to an instance of an object.
   at CQFollowerAutoclaimer.Form1.DQCalcBox_CheckedChanged(Object sender, EventArgs e)
   at System.Windows.Forms.CheckBox.OnCheckedChanged(EventArgs e)
   at System.Windows.Forms.CheckBox.set_CheckState(CheckState value)
   at System.Windows.Forms.CheckBox.set_Checked(Boolean value)
   at CQFollowerAutoclaimer.AutoDQ.loadDQSettings()
   at CQFollowerAutoclaimer.AutoDQ..ctor(Form1 m)
   at CQFollowerAutoclaimer.Form1..ctor()
   at CQFollowerAutoclaimer.Program.Main()
8/17/2018 3:16:08 PM
System.NullReferenceException: Object reference not set to an instance of an object.
   at CQFollowerAutoclaimer.Form1.DQCalcBox_CheckedChanged(Object sender, EventArgs e)
   at System.Windows.Forms.CheckBox.OnCheckedChanged(EventArgs e)
   at System.Windows.Forms.CheckBox.set_CheckState(CheckState value)
   at System.Windows.Forms.CheckBox.set_Checked(Boolean value)
   at CQFollowerAutoclaimer.AutoDQ.loadDQSettings()
   at CQFollowerAutoclaimer.AutoDQ..ctor(Form1 m)
   at CQFollowerAutoclaimer.Form1..ctor()
   at CQFollowerAutoclaimer.Program.Main()

ErrorLog.txt
8/17/2018 1:17:06 PM
8/17/2018 1:17:10 PM
	Error Cloud Script Error: level super {"ok":false,"err":"Server error"}
8/17/2018 1:17:10 PM
8/17/2018 1:17:14 PM
	Error Cloud Script Error: level super {"ok":false,"err":"Server error"}
8/17/2018 1:17:14 PM
8/17/2018 1:17:18 PM
	Error Cloud Script Error: level super {"ok":false,"err":"Server error"}
8/17/2018 1:17:18 PM
8/17/2018 1:17:22 PM
	Error Cloud Script Error: level super {"ok":false,"err":"Server error"}
8/17/2018 1:17:22 PM
8/17/2018 1:17:26 PM
	Error Cloud Script Error: level super {"ok":false,"err":"Server error"}
8/17/2018 1:41:31 PM
8/17/2018 1:41:35 PM
	Error Cloud Script Error: level super {"ok":false,"err":"Server error"}
8/17/2018 1:41:35 PM
8/17/2018 1:41:39 PM
	Error Cloud Script Error: level super {"ok":false,"err":"Server error"}
8/17/2018 1:41:39 PM
8/17/2018 1:41:43 PM
	Error Cloud Script Error: level super {"ok":false,"err":"Server error"}
8/17/2018 1:41:43 PM
8/17/2018 1:41:47 PM
	Error Cloud Script Error: level super {"ok":false,"err":"Server error"}
8/17/2018 1:41:47 PM
8/17/2018 1:41:51 PM
	Error Cloud Script Error: level super {"ok":false,"err":"Server error"}
8/17/2018 2:11:42 PM
8/17/2018 2:11:45 PM
	Error Cloud Script Error: level super {"ok":false,"err":"Server error"}
8/17/2018 2:11:46 PM
8/17/2018 2:11:49 PM
	Error Cloud Script Error: level super {"ok":false,"err":"Server error"}
8/17/2018 2:11:49 PM
8/17/2018 2:11:53 PM
	Error Cloud Script Error: level super {"ok":false,"err":"Server error"}
8/17/2018 2:11:53 PM
8/17/2018 2:11:57 PM
	Error Cloud Script Error: level super {"ok":false,"err":"Server error"}
8/17/2018 2:11:58 PM
8/17/2018 2:12:01 PM
	Error Cloud Script Error: level super {"ok":false,"err":"Server error"}

I'm interested in knowing what all those date/times with blank lines are for.
