### ISSUE TITLE
Crash and Exceptionlog info

### ISSUE THREAD

**Issue by Vitae666** [Wiedmolol/CQAutomater#9]
Just crashed. Says something about needing to be logged in. But isn't that what the Automater does?

5/4/2018 1:06:11 AM
System.AggregateException: One or more errors occurred. ---> System.Exception: Must be logged in to call this method
   at PlayFab.PlayFabClientAPI.<ExecuteCloudScriptAsync>d__77.MoveNext()
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   at System.Threading.Tasks.Task`1.get_Result()
   at CQFollowerAutoclaimer.PFStuff.GetGameData()
   at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()
---> (Inner Exception #0) System.Exception: Must be logged in to call this method
   at PlayFab.PlayFabClientAPI.<ExecuteCloudScriptAsync>d__77.MoveNext()<---

**Comment by Wiedmolol** [comment]
Should be fixed in the current version.
